"""Convert upstream rigged Blender meshes to eight baked, textured OBJ poses."""
import bpy, json, pathlib, urllib.request
from PIL import Image
from mathutils import Vector
root=pathlib.Path(__file__).resolve().parents[2]
out=root/'assets/mobs'
meta=json.loads((out/'SOURCES.json').read_text())
url=f'https://raw.githubusercontent.com/maikerumine/mobs_mc/{meta["skins_revision"]}/textures/mobs_mc_sheep_fur.png'
if not (out/'sheep-fur.png').exists():
    urllib.request.urlretrieve(url,out/'sheep-fur.png')
if not any(f['file']=='sheep-fur.png' for f in meta['files']):
    meta['files'].append({'file':'sheep-fur.png','url':url})
names=['sheep','zombie','villager','golem','creeper','cow','pig']
heights=[1.3,1.9,1.95,2.9,1.7,1.4,0.95]
rust='// Downloaded model poses: generated by work/export-mobs.py.\n'
rust+='pub const POSES: [[&str; 8]; 7] = [\n'
for name,height in zip(names,heights):
    bpy.ops.wm.open_mainfile(filepath=str(out/(('villager-rig' if name=='villager' else name)+'.blend')))
    scene=bpy.context.scene
    objects=[o for o in scene.objects if o.type=='MESH']
    if name=='cow': objects=[o for o in objects if o.name.startswith('cow_')]
    if name=='pig': objects=[o for o in objects if o.name.startswith('pig_')]
    if name=='creeper': objects=[o for o in objects if o.name.endswith('1')]
    if name=='villager': objects=[o for o in objects if o.name in ('evo_leg.left','evo_leg.right','evo_body','evo_nose','evo_head','evo_arm.middle','evo_coat1')]
    scene.frame_set(0)
    dep=bpy.context.evaluated_depsgraph_get()
    points=[o.matrix_world@v.co for o in objects for v in o.evaluated_get(dep).data.vertices]
    low=min(p.z for p in points); scale=height/(max(p.z for p in points)-low)
    center_x=(max(p.x for p in points)+min(p.x for p in points))*.5
    center_y=(max(p.y for p in points)+min(p.y for p in points))*.5
    skin=Image.open(out/(name+'.png')).convert('RGBA')
    if name=='sheep':
        fur=Image.open(out/'sheep-fur.png').convert('RGBA').resize(skin.size,Image.Resampling.NEAREST)
        atlas=Image.new('RGBA',(skin.width*2,skin.height)); atlas.paste(skin,(0,0));atlas.paste(fur,(skin.width,0));skin=atlas
    skin.save(out/(name+'-atlas.png'))
    for pose in range(8):
        scene.frame_set(300+pose*5 if name=='villager' else pose*5)
        dep=bpy.context.evaluated_depsgraph_get()
        lines=['# 22i GPL-3.0 model; licensed replacement skins: UPSTREAM-CREDITS.md','g Body','usemtl Skin']
        index=1
        for o in objects:
            evaluated=o.evaluated_get(dep); mesh=evaluated.to_mesh(); mesh.calc_loop_triangles()
            assert mesh.uv_layers, (name,o.name)
            mat=o.matrix_world; nm=mat.to_3x3().inverted().transposed()
            for tri in mesh.loop_triangles:
                for loop_index in tri.loops:
                    loop=mesh.loops[loop_index]; p=mat@mesh.vertices[loop.vertex_index].co; n=(nm@loop.normal).normalized()
                    uv=mesh.uv_layers.active.data[loop_index].uv
                    # This skin has a three-pixel gutter and two 32-pixel vertical variants.
                    u=(uv.x+3/64+(1 if o.name.startswith('fur.') else 0))/2 if name=='sheep' else uv.x
                    v=1-(1-uv.y)/2 if name=='sheep' else uv.y
                    lines += [f'v {-(p.x-center_x)*scale:.6f} {(p.z-low)*scale:.6f} {(p.y-center_y)*scale:.6f}',f'vt {u:.6f} {v:.6f}',f'vn {-n.x:.6f} {n.z:.6f} {n.y:.6f}']
                lines.append('f '+' '.join(f'{j}/{j}/{j}' for j in range(index,index+3)));index+=3
            evaluated.to_mesh_clear()
        assert index>100
        (out/f'{name}-{pose}.obj').write_text('\n'.join(lines)+'\n')
    rust+='['+','.join(f'include_str!("../assets/mobs/{name}-{p}.obj")' for p in range(8))+'],\n'
    print(name,len(objects),index-1,'vertices',height,'m')
rust+='];\npub const SKINS: [&[u8]; 7] = [\n'+','.join(f'include_bytes!("../assets/mobs/{n}-atlas.png")' for n in names)+'\n];\n'
if (root/'src').is_dir():
    (root/'src/mob_assets.rs').write_text(rust)
meta['conversion']='Eight baked walk poses, rotated to Y-up, real-world mob height, triangulated; replacement skins from mobs_mc. Original Blender sources retained under GPL-3.0.'
import hashlib
meta['adapted_files']={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(out.glob('*.obj'))+sorted(out.glob('*-atlas.png'))}
(out/'SOURCES.json').write_text(json.dumps(meta,indent=2))
