"""Bake distinct reports, outdoor echoes and weapon-specific mechanisms."""
import json
import pathlib
import wave
import numpy as np

root = pathlib.Path(__file__).resolve().parents[2]
out = root/'assets/audio'
rate = 44100
names = ['ak74u','ak74','akm','m4a1','famas','m16a4','m79','m200','tundra','aw50','svd','mp5k']
# Bass, dry decay, crack brightness, tail duration, peak, reflection spacing.
profiles = [
    (118,.045,5100,1.10,.60,.073), (94,.058,4100,1.35,.62,.088),
    (73,.075,3400,1.65,.66,.103), (128,.042,5500,1.20,.59,.081),
    (157,.037,6100,1.05,.58,.064), (113,.050,4700,1.45,.62,.093),
    (48,.125,900,2.4,.73,.158), (42,.165,3900,6.4,.90,.212),
    (62,.135,4500,5.8,.87,.187), (31,.215,3100,7.6,.91,.247),
    (81,.105,4200,3.9,.83,.143), (184,.031,6400,.9,.53,.054),
]

def lowpass(signal, cutoff):
    frequencies = np.fft.rfftfreq(len(signal), 1/rate)
    return np.fft.irfft(np.fft.rfft(signal)/(1+(frequencies/cutoff)**4), n=len(signal))

def noise(rng, size, cutoff):
    data = lowpass(rng.normal(0,1,size), cutoff)
    return data/max(.01,float(np.sqrt(np.mean(data*data))))

def write(name, signal, peak):
    signal = np.tanh(signal*.7)
    signal -= signal.mean(axis=0)
    signal *= peak/max(.01,float(abs(signal).max()))
    n = len(signal)
    fade = np.minimum(1,np.arange(n)/22)*np.minimum(1,(n-1-np.arange(n))/1400)
    signal *= fade[:,None]
    data = np.round(signal*32767).astype('<i2')
    assert np.all(data[0]==0) and np.all(data[-1]==0)
    assert np.max(abs(data.astype(np.int32)))<30000
    with wave.open(str(out/name),'wb') as wav:
        wav.setnchannels(2); wav.setsampwidth(2); wav.setframerate(rate)
        wav.writeframes(data.tobytes())
    rms = lambda start,end: float(np.sqrt(np.mean(signal[int(start*rate):int(end*rate)]**2))) if end>start else 0.
    return {'duration':n/rate,'peak':float(abs(signal).max()),
            'attack_rms':rms(0,.2),'tail_rms':rms(.5,min(1.,n/rate)),
            'late_rms':rms(3.,4.) if n/rate>=4 else 0.}

report = {}
for gun,(bass,decay,brightness,duration,peak,spacing) in enumerate(profiles):
    rng = np.random.default_rng(923901+gun*317)
    t = np.arange(int(rate*duration))/rate
    blast = noise(rng,len(t),brightness)*np.exp(-t/decay)*.65
    crack = rng.normal(0,1,len(t))-lowpass(rng.normal(0,1,len(t)),1800)
    blast += crack*np.exp(-t/(.014 if gun in (7,8,9,10) else .006))*(.06 if gun==6 else .45)
    blast += noise(rng,len(t),340)*np.exp(-t/(decay*1.6))*.65
    blast += np.sin(2*np.pi*bass*t)*np.exp(-t/(decay*1.5))*.38
    blast += np.sin(2*np.pi*(830+gun*137)*t)*np.exp(-t/.018)*.035
    stereo = np.column_stack((blast,blast))
    sniper = gun in (7,8,9,10)
    for channel in range(2):
        for echo in range(1,24 if sniper else 9):
            delay = spacing*echo*(1+echo*.047)+channel*(.007+echo*.0017)
            offset = int(delay*rate)
            if offset>=len(t): break
            gain = (.33 if sniper else .16)*np.exp(-delay/(duration*.27))
            reflected = lowpass(blast, max(450,brightness/(1+echo*.24)))
            stereo[offset:,channel] += reflected[:-offset]*gain
        diffuse = noise(rng,len(t),1400 if sniper else 2400)
        envelope = (1-np.exp(-t*15))*np.exp(-t/(duration*.22))
        stereo[:,channel] += diffuse*envelope*(.06 if sniper else .009)
    report[names[gun]] = write(names[gun]+'-shot.wav',stereo,peak)
    for event in range(3):
        duration = [.42,.40,.34][event]+(.20 if gun==6 else .13 if gun in (7,8,9) else gun*.003)
        t = np.arange(int(rate*duration))/rate
        signal = np.zeros(len(t))
        times = [.016,.092,.225] if event==0 else [.012,.065,.190] if event==1 else [.012,.120,.245]
        for j,at in enumerate(times):
            at += gun*.0019
            q = np.maximum(0,t-at)
            metal = noise(rng,len(t),1700+gun*115)
            ring = np.sin(2*np.pi*(350+gun*81+event*127+j*227)*q)
            signal += (metal*.34+ring*.16)*np.exp(-q*(60+j*24))*(t>=at)
            slide = .09 if gun in (7,8,9) else .065 if gun==6 else .03
            signal += noise(rng,len(t),800)*np.exp(-((t-at-slide)/slide)**2)*.09
        write(names[gun]+['-out.wav','-in.wav','-bolt.wav'][event],
              np.column_stack((signal,signal*.97)),.38 if gun==6 else .32)

for name in ('m200','tundra','aw50'):
    assert report[name]['duration']>=5.5
    assert report[name]['peak']>.85 and report[name]['late_rms']>.001
    assert report[name]['attack_rms']>max(report[n]['attack_rms'] for n in ('m4a1','famas','mp5k'))
assert len(list(out.glob('*.wav')))==48
(out/'ANALYSIS.json').write_text(json.dumps(report,indent=2),encoding='utf-8')
rust = '// Original stereo PCM assets, generated by work/prepare-audio-v19.py.\npub const WEAPON_AUDIO: [[&[u8]; 4]; 12] = [\n'
for name in names:
    rust += '['+','.join(f'include_bytes!("../assets/audio/{name}-{event}.wav")' for event in ('shot','out','in','bolt'))+'],\n'
if (root/'src').is_dir():
    (root/'src/weapon_audio.rs').write_text(rust+'];\n',encoding='utf-8')
(out/'SOURCES.md').write_text('Original stereo sound design for VOXEL 1.9, 44.1 kHz / 16-bit PCM.\n48 distinct reports and mechanisms. Layered broadband muzzle blasts, low-frequency pressure, metal latches, receiver resonances, stereo reflections and diffuse outdoor decay.\nM200, Tundra and AW50 have 5.8–7.6 second decays and higher attack energy; SVD has a 3.9 second tail.\nNo third-party recordings. Licensed under the project MIT license. ANALYSIS.json records measured levels and tails.\n',encoding='utf-8')
print(json.dumps(report,indent=2))
